# Generated by Django 3.1.12 on 2025-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('husbandname', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=20)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
