from django.urls import path
#now import the views.py file into this code
from . import views
from django.conf import settings
urlpatterns=[
  path('',views.index, name='index'),
  path('patient_login/', views.patient_login, name='patient_login'),
  path('doctor_login/', views.doctor_login, name='doctor_login'),
  path('lab_login/', views.lab_login, name='lab_login'),
  path('admin_login/', views.admin_login, name='admin_login'),
  path('patient_register/', views.patient_register, name='patient_register'),
  path('doctor_register/', views.doctor_register, name='doctor_register'),
  path('lab_register/', views.lab_register, name='lab_register'),
  path('save_patient/', views.save_patient, name='save_patient'),
  path('save_doctor/', views.save_doctor, name='save_doctor'),
  path('save_lab_technician/', views.save_lab_technician, name='save_lab_technician'),
  path('admin_login_check/', views.admin_login_check, name='admin_login_check'),
  path('view_lab_technicians/', views.view_lab_technicians, name='view_lab_technicians'),
  path('lab_technician_login_check/', views.lab_technician_login_check, name='lab_technician_login_check'),
  path('predict_save/', views.predict_save, name='predict_save'),
  path('lab_report_view/', views.lab_report_view, name='lab_report_view'),
  path('delete_report/', views.delete_report, name='delete_report'),
  path('technician_upload_page/', views.technician_upload_page, name='technician_upload_page'),
  path('doctor_report_view/', views.doctor_report_view, name='doctor_report_view'),
  path('technician_upload_page/', views.technician_upload_page, name='technician_upload_page'),
  path('doctor_individual_view/', views.doctor_individual_view, name='doctor_individual_view'),
  path('doctor_login_check/', views.doctor_login_check, name='doctor_login_check'),
  path('patien_login_check/', views.patien_login_check, name='patien_login_check'),
  path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
  path('view_patient_reports/', views.view_patient_reports, name='view_patient_reports'),
  path('health_tips_patient/', views.health_tips_patient, name='health_tips_patient'),
  path('food_tips_patient/', views.food_tips_patient, name='food_tips_patient'),
  path('buy_products/', views.buy_products, name='buy_products'),
  path('index_page/', views.index_page, name='index_page'),
  path('view_admin_page/', views.view_admin_page, name='view_admin_page'),
  path('view_admin_doctors/', views.view_admin_doctors, name='view_admin_doctors'),
  path('view_admin_technician/', views.view_admin_technician, name='view_admin_technician'),
  path('view_admin_user/', views.view_admin_user, name='view_admin_user'),
  path('patient_individual_view/', views.patient_individual_view, name='patient_individual_view'),
  path('doctor_report_view/', views.doctor_report_view, name='doctor_report_view'),
  path('book_appointments/', views.book_appointments, name='book_appointments'),
  path('save_appointment/', views.save_appointment, name='save_appointment'),
  path('view_all_appointments/', views.view_all_appointments, name='view_all_appointments'),
  path('doctor_view_appointments/', views.doctor_view_appointments, name='doctor_view_appointments'),
]